import Head from 'next/head'
const login = () => {
   return (
      <div>
         <Head>
            <title>N Pro | Login</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <h2>Login</h2>
      </div>
   )
}

export default login